name: Substr CI

on:
  pull_request

jobs:
  tests:
    name: Testing substr
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: |
        sudo apt install binutils g++ cmake
        sudo apt install haskell-stack netbase
    - name: setup tests
      run: stack setup && stack build
    - name: build
      run: bash build.sh
    - name: run debug tests
      run: stack run _build_debug_san/solution
    - name: run rwdi tests
      run: stack run _build_rwdi_san/solution
    - name: run release tests
      run: stack run _build_release/solution
